Better DevEx
defenseunicorns/uds-infrastructure-software-factory-aws pull request #19
Opened 2023-09-06 01:22 UTC by justin-o12

Using SSM Parameters to pass values from one stack to the other, centralizing one tfvars file to edit, and outputting a yaml file to be used by Zarf.

2023-09-06 12:58 UTC, zachariahmiller requested changes
See my comment on the local file. Will approve after that gets updated.

2023-09-06 12:58 UTC, zachariahmiller commented on gitlab/main.tf
> +resource "local_file" "output_file" {
Can you please make this conditional? This doesn't just work without merging another zarf-config yaml (DUBBD values) and zarf doesn't support multiple config.yaml.

2023-09-12 21:54 UTC, zachariahmiller approved these changes
LGTM!

2023-09-13 16:39 UTC, merged

2023-09-13 17:14 UTC, mikevanhemert approved these changes